# ProGuard / R8 rules auto-generated by CodXFuse
-keepattributes *Annotation*, InnerClasses, EnclosingMethod, Signature, Exceptions
-dontwarn androidx.**
-keep class androidx.** { *; }

# Kotlin Coroutines
-dontwarn kotlinx.coroutines.**
-keepclassmembers class kotlinx.coroutines.** { *; }

# Jetpack Compose
-keep class androidx.compose.ui.platform.** { *; }
-keep class androidx.compose.runtime.** { *; }

# Maintain line numbers for debugging & crash reports
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
